ha = int(input("digite o valor da hora aula:"))
ht = int(input("digite a quantidade de horas trabalhadas:"))
salário = (ha * ht)
ir = (salário/100*11)
inss = (salário/100*8)
sind = (salário/100*5)
print("salario bruto:",salário)
print("imposto de renda:",ir)
print("inss:",inss)
print("contribuição sindical:",sind)
print("salario liquido:",salário-ir-inss-sind)
